### ISSUE TITLE
Two SMS message variants - notify family, trusted contact

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#10]

**Comment by ivanovivan12589** [comment]
Does it mean that when you enter a false password, PTelegram should sends SMS to either family or trusted contact?

**Comment by wrwrabbit** [comment]
both.
2 contacts, each with their own message

**Comment by ivanovivan12589** [comment]
Just to make sure I understand the problem correctly: I need to add another contact with its own phone number and message and rename contacts to "Family contact" and "Trusted contact", right?

**Comment by wrwrabbit** [comment]
Yes
