### ISSUE TITLE
Шифрование сообщений и файлов с помощью AES

### ISSUE THREAD

**Issue by vivabelarus** [wrwrabbit/Partisan-Telegram-Android#100]
Шифрование сообщений и файлов с помощью AES перед отправкой (допустим docx, txt, png) - зажимаем по файлу вводим желаемый пароль, отсылается уже надежно зашифрованный файл, при выходе из чата пароль удаляется. При получении файла .aes при клике просит пароль, расшифровка, открытие из временной памяти файла, после закрытии удаляется (при желании). Пароль можно передавать при личной встрече или секретном чате. Сообщения — зажимаем отправить и видим новый подпункт — зашифровать. Расшифровка так же как и с файлом.

**Comment by huntmix** [comment]
https://github.com/huntmix/securityaddon/blob/main/app/src/main/java/com/huntmix/secbutton/Api.java

**Comment by vivabelarus** [comment]
Думаю, при желании, можно отправлять зашифрованный архив. Не думаю, что такая функция будет востребована
