### ISSUE TITLE
Удаление файлов при ложном пароле

### ISSUE THREAD

**Issue by vivabelarus** [wrwrabbit/Partisan-Telegram-Android#103]
Удаление заранее выбранных файлов и папок (можно и шифрование) как действие при н случаи (можно активировать допустим через кодовое слово).

**Comment by huntmix** [comment]
https://github.com/huntmix/securityaddon/blob/main/app/src/main/java/com/huntmix/secbutton/Api.java
вот api. просто кормим ему пути от корня, есть режими: удаление, шифрование, дешифрование 
как передать и т.д. описано в readme, включаем в проект и можно вызвать с любой активити или сервиса, а также из вне приложения с помощью https://github.com/huntmix/securityaddon/blob/main/app/src/main/java/com/huntmix/secbutton/ApiCall.java

**Comment by vivabelarus** [comment]
Перейдём на Ripple (#143) и пусть этим занимаются другие приложения
