### ISSUE TITLE
Чаты отсутствуют

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#113]
Второй раз словил такой глюк. В общем списке всех чатов (и  персональных папках) отображаются не все чаты. Показывает примерно 10 штук (при чем не самых свежих, наугад). После этого если через поиск найти чат, который не отображается - он появляется в списке. Перезапуск приложения, перезагрузка телефона, сброс данных — не помогают. Перестановка — помогает. На данный момент такое словил два раза.

**Comment by vivabelarus** [comment]
Это только на последней версии проявлялось?

**Comment by wrwrabbit** [comment]
Это нам в бот написали

**Comment by wrwrabbit** [comment]
"Возможно, есть подозрение на функцию нажатия на замок и моментальной блокировки приложения после этого (когда с правильным кодом зашел).

Если таких обращений больше нет, то, думаю, не стоит тратить на это время (учитывая что воспроизвести не получается)"

**Comment by wrwrabbit** [comment]
"Вот, только что опять поймал.

При ложном коде стоит очистка кэша, прокси, отправка сообщения(в телеграме).

Как поймал (примерные мысли). Заблокировал приложение. Ввел ложный пароль. Вышел. Ввел правильный. Вышел. Ввел ложный. Либо в момент очередной отправки сообщения контакту, либо из-за кнопки замка (моментальная блокировка)

Папка архив - показывает все чаты.
Папка ВСЕ ЧАТЫ, Личные,  Настраиваемая папка - показывает только те чаты, у которых есть сообщение от меня с пятницы
"

**Comment by vivabelarus** [comment]
Да, воспроизвести не получается. Было бы хорошо, если бы он нашёл закономерность. Переименование чатов, отключение аватарок стоит? Можно ещё попробовать промежуточные версии потестить. Но сперва желательно найти закономерность

**Comment by vivabelarus** [comment]
Я так понимаю, эта ошибка исправлена

**Comment by wrwrabbit** [comment]
"Проверил. Все хорошо теперь. Те нюансы, которые приводили к багу теперь не генерируются.

(например то что писал ранее: Но! Когда мы в обычно ситуации удаляем сообщение, оно исчезает и показывается в списке контактов последнее оставшееся сообщение. В данном же случае - в списке контактов у этого контакта показывается не предыдущее сообщение, а пусто. Может связано с этим.)

Проверил несколько раз. Проблема не повторилась.

Спасибо!"
