### ISSUE TITLE
False password setting is missing

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#116]
Ранее установленный ложный пароль не отображается в списке ложных паролей. Соответственно настраивать что-то нереально по ложному паролю 1. Другими словами: при накатывании новой версии - ложный пароль 1 уже не отображается в настройках.

**Comment by vivabelarus** [comment]
На каких версиях это проявилось? Похожая проблема появилась в 2.3.4 и была исправлена в 2.3.7. На версиях, опубликованных на канале (2.3.3, 2.4.1, 2.5.1) у меня не получилось воспроизвести.

**Comment by wrwrabbit** [comment]
"версия 2.5.1? 
- Да. Откат на более старую версию не помог (2.3.3)
"

**Comment by vivabelarus** [comment]
А можно подробнее, как это воспроизвести? Пропал пароль. И новый тоже не удаётся создать? Или старый пропал и больше не появляется, даже после отката?

**Comment by wrwrabbit** [comment]
"...первый нет. Создал новый, работает ли первый хз"

**Comment by vivabelarus** [comment]
Короче. Видимо, пользователь тестировал какую-то из версий 2.3.4 - 2.3.6. Там был баг, связанный с тем, что сохранённый код-пароль невозможно было загрузить. Если новый код-пароль работает нормально, я так понимаю, проблема решена.
