### ISSUE TITLE
Переделка activity выбора чатов для удаления

### ISSUE THREAD

**Issue by vivabelarus** [wrwrabbit/Partisan-Telegram-Android#118]
Есть следующие проблемы:

1. Если чат был удалён, все приходящие сообщения тоже будут удаляться. Это было реализовано в рамках #19. Такое поведение не очень очевидно для пользователя, оно должно быть опциональным.
2. Иногда не нужно, чтобы чат удалялся, он должен просто скрываться. Например, если в чате дорогая переписка за многие годы. 

Поэтому необходимо сделать отдельную activity, примерно такую же, как `FakePasscodeTelegramMessagesActivity.java`. Наверное, тоже с диалогом, который будет появляться при выборе чата, в котором можно настроить опции для чата. В рамках этого issue не обязательно реализовывать функционал, который исправит вышеуказанные проблемы. Можно просто сделать activity со своим диалогом, а реализацию опций оставить на потом.

**Comment by wrwrabbit** [comment]
Можно в списке чатов сделать галочку "очистить"

**Comment by vivabelarus** [comment]
Это про что? Про то, как будет выглядеть эта activity?

**Comment by wrwrabbit** [comment]
Я о том что мб нет необходимости делать отдельную activity, можно сделать checkbox в самом списки, на каждой строке

**Comment by vivabelarus** [comment]
А, понял. Если говорить про саму activity, то её неплохо было бы сделать новую. Просто потому что старая не очень расширяема, будут уродливые ифы. 

И там прикол в том, что одним checkbox'ом не отделаться. Нужно хотя бы два. Один про удаление/скрытие чата, а второй про удаление всех новых сообщений. Можно не checkbox на каждой строке, а 3 точки, при нажатии на которые появится менюшка с этими чекбоксами.

**Comment by vivabelarus** [comment]
А ещё для удаления/скрытия чата лучше использовать не checkbox'ы, а radio button'ы. Только хз, как их тогда красиво сделать.

**Comment by vivabelarus** [comment]
Я тут подумал. А если сделать так, чтобы диалог появлялся при долгом нажатии на чат? Вроде, реализовать достаточно просто, не надо глобальных переделок. Но на сколько это будет очевидно для юзера?

**Comment by wrwrabbit** [comment]
Не надо, не интуитивно

**Comment by vivabelarus** [comment]
Closed in #176
