### ISSUE TITLE
Иконка партизанской телеги отличается от оригинальной?

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#120]
Мне кажется, что иконка партизанской телеги отличается от оригинальной: отсутствует фоновая прозрачность. Хорошо видно при темной теме.

сейчас иконка выглядит так
![5655543](https://user-images.githubusercontent.com/76569803/118541974-080e6480-b75b-11eb-9520-a4436c11ba64.jpeg)

А было без белого фона.

**Comment by vivabelarus** [comment]
Иконку мы не меняли. Это какая-то проблема оригинальной версии. Почему-то у некоторых она с белой обводкой, у некоторых без
