### ISSUE TITLE
'app not installed' on some devices

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#13]
Honor 20 pro, Android 10

**Comment by Nill-R** [comment]
![photo_2021-01-23_13-57-06](https://user-images.githubusercontent.com/47075922/105577572-2a7f0b00-5d83-11eb-98ff-eece34182f89.jpg)
Same shits
Trouble with app name and version
Conflict with real Telegram

**Comment by wrwrabbit** [comment]
@Nill-R  Looks like you didn't remove the original Telegram app

**Comment by wrwrabbit** [comment]
Possible solutions
https://www.digitbin.com/app-not-installed-fix-error/

**Comment by wrwrabbit** [comment]
Android 8.0 Huawei P8 - Original telegram was removed but issue still exists

**Comment by wrwrabbit** [comment]
если телега стояла во втором пространстве, то не установит. Надо сначала снести телегу из первого, а потом и во втором. Обычно это не мешает. Но в данном случае начинает психовать, что такой пакет уже есть в системе.
