### ISSUE TITLE
Handle multiple accounts in one app

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#15]

**Comment by ByArm** [comment]
Highly appreciated !

**Comment by vivabelarus** [comment]
What do you mean? You can have up to 3 account in one app.

**Comment by wrwrabbit** [comment]
That's what I meant. I just wasn't sure if it's supported+tested in PTelegram

**Comment by NektoIzBelarusi** [comment]
Better to do something like that:
3 pin-codes. 1st - opens PG with up to 3 your "official" accounts. 2nd - opens parallel space up to 3 unofficial. And 3rd pin-code is false pin-code for all. It opens official zone (1-3 accounts) and destroys all selected chats and groups in all accounts.
