### ISSUE TITLE
Закрытие приложения после блокировки телефона (а-ля свайпом)

### ISSUE THREAD

**Issue by ultramaks** [wrwrabbit/Partisan-Telegram-Android#159]
Если в приложении установлен пароль. то после блокировки телефона из приложения и его разблокировки сначала надо ввести пароль от телефона, а потом еще и пароль от приложения, которое остается на экране. Иногда это может приводить к "конфузам", мол человек вроде ввел правильный пароль от телефона, а телефон не пускает (хотя это уже пароль для приложения запрашивается). Да и вообще, лучше лишний раз не светить приложение, даже если оно и было последним перед блокировкой телефона.
Можно ли реализовать такую фичу, что после блокировки телефона приложения закрывается для главного экрана (словно мы его свайпнули) и попасть в него можно было только тапнув на его иконку?

**Comment by vivabelarus** [comment]
Да, можно такое попробовать реализовать
