### ISSUE TITLE
Background notifications not working

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#16]
В приложении Птелеграм наблюдаются сбои с уведомлениями. В заблокированном состоянии отсутствуют уведомления на экране блокировки. Samsung galaxy s10

**Comment by AngrySamaritan** [comment]
Galaxy a50 та же проблема

**Comment by wrwrabbit** [comment]
Fix by adjusting the GCM settings in https://my.telegram.org/apps
