### ISSUE TITLE
Нет ограничения количества цифр при вводе ложного номера телефона

### ISSUE THREAD

**Issue by radischel** [wrwrabbit/Partisan-Telegram-Android#165]
После ввода 12 цифр для ложного номера телефона - телефон имеет вид: +111 (11) 111-11-11
После ввода 13 цифр: +111 (111) 111-11-11
После ввода 14 цифр и более: +111 11111111111
![1](https://user-images.githubusercontent.com/88798603/129093745-2241ff98-6222-48b0-a8cf-f2d2b2b03e7f.jpg)
![2](https://user-images.githubusercontent.com/88798603/129093873-38562da3-01b4-4282-a6c5-e96a5736d52b.jpg)

**Comment by vivabelarus** [comment]
Подсказка по формату номера добавлена. Сам формат номера не проверяется, так как сложно предусмотреть все возможные форматы номера
