### ISSUE TITLE
Reproducible builds not working when using docker build

### ISSUE THREAD

**Issue by SergeHill** [wrwrabbit/Partisan-Telegram-Android#17]
Если тестировать билд на соответствие исходникам, то получается отрицательный результат.
Сравнивал APK 1.0 и release/tag "1.0" 
Использую вот этот мануал https://core.telegram.org/reproducible-builds
Сократил пару шагов - получение апк в частности.
На оригинальном телеграмме работает на ура.
На местном - отличие в куче файлов, 
Часть из них - изображение, часть - бинарные файлы и java код.
Если использовать apkdiff.py, то сам по себе он говорит что apk разные, если закомментить return false, то можно получить полный список:

```
APK file res/drawable-hdpi-v4/ic_action_pause.png does not match
APK file res/drawable-xhdpi-v4/ft_avd_toarrow.png does not match
APK file lib/armeabi-v7a/libtmessages.35.so does not match
APK file res/drawable-xhdpi-v4/ic_fingerprint_error.png does not match
APK file res/drawable-xhdpi-v4/buy_with_googlepay_button_content.png does not match
APK file res/drawable-xxhdpi-v4/ic_action_next.png does not match
APK file res/drawable-xhdpi-v4/ic_action_pause.png does not match
APK file lib/arm64-v8a/libtmessages.35.so does not match
APK file res/drawable-xhdpi-v4/ic_action_next.png does not match
APK file res/drawable-xxhdpi-v4/ft_avd_toarrow.png does not match
APK file res/drawable-hdpi-v4/ic_action_previous.png does not match
APK file res/drawable-hdpi-v4/ic_action_play.png does not match
APK file res/drawable-mdpi-v4/ic_action_pause.png does not match
APK file lib/x86_64/libtmessages.35.so does not match
APK file res/drawable-hdpi-v4/ic_fingerprint_error.png does not match
APK file classes3.dex does not match
APK file classes.dex does not match
APK file res/drawable-mdpi-v4/googlepay_button_content.png does not match
APK file res/drawable-mdpi-v4/ft_avd_tooverflow.png does not match
APK file res/drawable-xxhdpi-v4/ft_avd_tooverflow.png does not match
APK file res/drawable-hdpi-v4/ic_action_next.png does not match
APK file lib/x86/libtmessages.35.so does not match
APK file res/drawable-hdpi-v4/ft_avd_toarrow.png does not match
APK file res/drawable-xhdpi-v4/ft_avd_tooverflow.png does not match
APK file res/drawable-hdpi-v4/ft_avd_tooverflow.png does not match
APK file res/drawable-mdpi-v4/ic_action_play.png does not match
APK file res/drawable-xxhdpi-v4/ic_action_play.png does not match
APK file res/drawable-xhdpi-v4/ic_action_play.png does not match
APK file res/drawable-xxhdpi-v4/buy_with_googlepay_button_content.png does not match
APK file res/drawable-mdpi-v4/ic_action_previous.png does not match
APK file res/drawable-mdpi-v4/ic_fingerprint_error.png does not match
APK file resources.arsc does not match
APK file res/drawable-xxhdpi-v4/ic_fingerprint_error.png does not match
APK file res/drawable-hdpi-v4/buy_with_googlepay_button_content.png does not match
APK file res/drawable-xxhdpi-v4/googlepay_button_content.png does not match
APK file res/drawable-mdpi-v4/ic_action_next.png does not match
APK file res/drawable-xhdpi-v4/ic_action_previous.png does not match
APK file res/drawable-mdpi-v4/buy_with_googlepay_button_content.png does not match
APK file res/drawable-mdpi-v4/ft_avd_toarrow.png does not match
APK file res/drawable-xhdpi-v4/googlepay_button_content.png does not match
APK file res/drawable-xxhdpi-v4/ic_action_pause.png does not match
APK file classes2.dex does not match
APK file res/drawable-hdpi-v4/googlepay_button_content.png does not match
APK file res/drawable-xxhdpi-v4/ic_action_previous.png does not match
```

Скрипт игнорирует некоторые конфиги.
Альтернитавно можно сравнить используя https://github.com/daniellockyer/apkdiff - тут тула сравнивает исходники и там довольно много изменений, самое страшное - бинарники.

Суть: как доверять билдам, если мы не можем проверить, что они действительно скомпилированы из данных исходников.
Возможно есть смысл озаботиться пайплайном, если он другой - параметры/тулы - то результат может быть иным.

**Comment by SergeHill** [comment]
Дополнительное стравнение, используя https://github.com/radekdoulik/apkdiff

```
apkdiff.exe --bs PTelegram-v1_0.apk app-p-1.apk
Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
  +     572,445 META-INF/CERT.SF *2
  +     572,390 META-INF/MANIFEST.MF *2
  +       1,377 META-INF/CERT.RSA *2
  +         456 resources.arsc
  +         249 res/drawable-xxhdpi-v4/ic_fingerprint_error.png
  +         205 res/drawable-hdpi-v4/ic_fingerprint_error.png
  +         194 res/drawable-xhdpi-v4/ic_fingerprint_error.png
  +         177 res/drawable-mdpi-v4/ic_fingerprint_error.png
  +         108 res/drawable-xhdpi-v4/ic_action_play.png
  +         104 classes.dex
    +           1 strings count
    +           1 fields count
    +           1 methods count
    +          84 data section size
  +          90 res/drawable-hdpi-v4/ic_action_play.png
  +          72 res/drawable-xxhdpi-v4/ic_action_pause.png
  +          60 res/drawable-mdpi-v4/ic_action_play.png
  +          57 res/drawable-xxhdpi-v4/ic_action_play.png
  +          41 res/drawable-xxhdpi-v4/ft_avd_toarrow.png
  +          33 res/drawable-xhdpi-v4/ft_avd_toarrow.png
  +          26 res/drawable-xxhdpi-v4/ft_avd_tooverflow.png
  +          24 res/drawable-hdpi-v4/ic_action_pause.png
  +          22 res/drawable-hdpi-v4/ft_avd_tooverflow.png
  +          18 res/drawable-xhdpi-v4/ft_avd_tooverflow.png
  +          17 res/drawable-xhdpi-v4/ic_action_pause.png
  +          16 res/drawable-mdpi-v4/ft_avd_toarrow.png
  +          15 res/drawable-hdpi-v4/ft_avd_toarrow.png
  +          14 res/drawable-mdpi-v4/ft_avd_tooverflow.png
  +           8 res/drawable-mdpi-v4/ic_action_previous.png
  +           5 res/drawable-mdpi-v4/ic_action_next.png
  +           3 res/drawable-mdpi-v4/ic_action_pause.png
  +           1 res/drawable-xhdpi-v4/ic_action_next.png
  -           4 res/drawable-hdpi-v4/ic_action_next.png
  -           7 res/drawable-hdpi-v4/ic_action_previous.png
  -           7 res/drawable-xhdpi-v4/ic_action_previous.png
  -          61 res/drawable-xxhdpi-v4/ic_action_next.png
  -          78 res/drawable-mdpi-v4/googlepay_button_content.png
  -         102 res/drawable-hdpi-v4/googlepay_button_content.png
  -         104 res/drawable-xxhdpi-v4/ic_action_previous.png
  -         173 res/drawable-mdpi-v4/buy_with_googlepay_button_content.png
  -         202 res/drawable-xhdpi-v4/googlepay_button_content.png
  -         259 res/drawable-hdpi-v4/buy_with_googlepay_button_content.png
  -         363 res/drawable-xxhdpi-v4/googlepay_button_content.png
  -         444 res/drawable-xhdpi-v4/buy_with_googlepay_button_content.png
  -         902 res/drawable-xxhdpi-v4/buy_with_googlepay_button_content.png
  -      12,288 lib/armeabi-v7a/libtmessages.35.so
  -      12,288 lib/arm64-v8a/libtmessages.35.so
  -      12,288 lib/x86_64/libtmessages.35.so
  -      12,288 lib/x86/libtmessages.35.so
Summary:
  +   1,145,417 Other entries 6.29% (of 18,203,890)
  -      49,152 Shared libraries -0.06% (of 83,175,456)
  +         104 Dalvik executables 0.00% (of 14,679,680)
  +     388,595 Package size difference 0.72% (of 54,030,243)
```

Больше всего удивляет   -      12,288 lib/armeabi-v7a/libtmessages.35.so
У моего билда "изкоробки" прилично меньше бинарники

**Comment by wrwrabbit** [comment]
Хмм, я подозреваю что причина различия в apk это разные версии Android Studio и SDK которыми он пользуется.
libtmessages.35.so компилируется во время билда проекта.

Все модификации которые мы делали в отношении оригинального Тг клиента можно просмотреть в наших комитах.
Вы пробовали сделать билд последней версии этой репо и сравнит с оригинальным тг клиентом?

**Comment by wrwrabbit** [comment]
Я могу порекомендовать вам сделать билд этой репо и сравнит с нашим apk, если все на ура то значит нашему билду можно доверять, если нет то надо будет уточнить почему нет.

**Comment by wrwrabbit** [comment]
Проверьте плиз release 1.1

**Comment by SergeHill** [comment]
Если не вдаваться в подробности, то бинарники не изменились, значительно изменилась java часть, часть классов и методов исчезла. по итогу различий стало ещё больше. Мой АПК тут https://file.io/GSdI7ROLZqSW
Какой пайплан у вас используется для билда?
Я для билда не использую Android Studio и прочие вещи, всё собирается в докере с фиксированными зависимостями.
Возможно вам стоит попытаться сделать так же.
Только в репе не хватает release keys, для теста я подставил из официальной телеги (на бинарники и код влиять не должно).

Прошу прощения, что отнимаю время. К сожалению в наше время недостаточно проверить исходники, люди начали спрашивать гарантии и reproducible builds - один из вариантов достоверной проверки.

**Comment by wrwrabbit** [comment]
Наш пайплайн заключается билдом через Android Studio 4.1.1 )
Опыта пайплайнов на докере нет, но с докерами работали так что особых проблем делать так release не должно быть. Если вы можете помочь отладить reproducible builds будем благодарны. 
Вы можете поделится docker файлом?

**Comment by SergeHill** [comment]
Docker file лежит прямо в корне репозитория :)
Шаги описаны тут:
https://core.telegram.org/reproducible-builds
По сути сводится всё к:
```
docker build -t telegram-build .
docker run --rm -v "$PWD":/home/source telegram-build
```
Результат в TMessagesProj/build/outputs/apk/

**Comment by wrwrabbit** [comment]
хахах, классический RTFM.

Ок, следующую версию будем так билдить

**Comment by wrwrabbit** [comment]
Не билдится в докере, включил stacktrace и debug но не пишет почему failed..
У вас таких проблем не было?

<img width="976" alt="Снимок экрана 2021-01-24 в 15 35 20" src="https://user-images.githubusercontent.com/76569803/105630405-10642c00-5e5a-11eb-8f42-b158650a4f8b.png">

**Comment by wrwrabbit** [comment]
@SergeHill ?

**Comment by wrwrabbit** [comment]
В вашем архиве есть только один apk https://file.io/GSdI7ROLZqSW

В процессе билда создаются 9 apk файлов. Вы какой тестировали? Нужно afatRelease проверять

**Comment by wrwrabbit** [comment]
Ок.
У меня машина попроще ) С AndroidStudio жрет оперативку но не крэшит, все таски заканчиваются.
"Мб вы поставили органичение на размер оперативной" - ограничение где? Я по инструкции все делал, хз

**Comment by wrwrabbit** [comment]
<img width="468" alt="354534" src="https://user-images.githubusercontent.com/76569803/106356082-cec9fa00-630d-11eb-99c4-72805009769d.png">
Ура! на мощном серваке билдится норм.

**Comment by wrwrabbit** [comment]
Closed by https://github.com/wrwrabbit/Partisan-Telegram-Android/releases/tag/1.1.2
