### ISSUE TITLE
Удаление стикеров

### ISSUE THREAD

**Issue by Bulbachka** [wrwrabbit/Partisan-Telegram-Android#18]
При вводе неверного пароля удалять выбранные наборы стикеров.

**Comment by wrwrabbit** [comment]
Я думаю достаточно удалить все стикеры. Нет необходимости делать особый UI для выбора стикеров на удаление, просто удалить все стикеры если юзер включил эту опцию.

**Comment by vivabelarus** [comment]
> 
> 
> Я думаю достаточно удалить все стикеры. Нет необходимости делать особый UI для выбора стикеров на удаление, просто удалить все стикеры если юзер включил эту опцию.

Вот отличнейшая идея. А то прям лень было отдельный ui под это делать.
