### ISSUE TITLE
Не показывать чат с кодами авторизации

### ISSUE THREAD

**Issue by osipxd** [wrwrabbit/Partisan-Telegram-Android#19]
Не знаю реализовано это или нет, но по диффам не нашел.
Хорошо бы, чтобы если введён фейковый пин, не отображался сервисный чат Telegram, в который падают одноразовые коды для авторизации на новом устройстве.

**Comment by wrwrabbit** [comment]
Хорошая идея ))

**Comment by vivabelarus** [comment]
Closed in #46
