### ISSUE TITLE
При повторном включении слетает цветовая тема.

### ISSUE THREAD

**Issue by Sandoplay** [wrwrabbit/Partisan-Telegram-Android#20]
Выбираю цветовую тему, всё хорошо, но стоит выгрузить ТГ из оперативки как тема слетает.
При том если зайти в настройки тем то галочка стоит на той теме которую выбирал.

**Comment by vivabelarus** [comment]
Код, касающийся цветовой темы не менялся в моде. Не могли бы Вы проверить, проявляется ли данная ошибка в оригинальном приложении. Если ошибка проявляется только в модифицированной версии приложения, пожалуйста, опишите действия, при помощи которых можно воспроизвести её.

**Comment by Sandoplay** [comment]
> Код, касающийся цветовой темы не менялся в моде. Не могли бы Вы проверить, проявляется ли данная ошибка в оригинальном приложении. Если ошибка проявляется только в модифицированной версии приложения, пожалуйста, опишите действия, при помощи которых можно воспроизвести её.

Проверил, в оригинальном всё работает.
В моде в настройках чатов меняем тему на ночную, выходим в главное меню телеграма, всё есть. Выгружаем телеграм из оперативки, всё, тема стандартная

**Comment by vivabelarus** [comment]
Может быть, у Вас ночная тема как-то особо настроена? Например, установлено включение ночной темы по расписанию.

**Comment by Sandoplay** [comment]
> Может быть, у Вас ночная тема как-то особо настроена? Например, установлено включение ночной темы по расписанию.

Чел ну я чё совсем дурак? Всё проверял, в оригинальном ТГ всё работает, в моде нет. Сам скачай мод и попробуй тему поставить

**Comment by vivabelarus** [comment]
Не удалось воспроизвести ошибку

**Comment by wrwrabbit** [comment]
"Уже несколько версий багует переключение на ночную тему и обратно в вечернее время. Телега внезапно сама по себе переключает тему. Ночная тема настроена по расписанию от заката до рассвета"

https://t.me/cpartisans_sec_chat/588

**Comment by lebovsky-z** [comment]
По поводу бага, описанного выше...телефон oneplus 7t pro, android 11. Находишься в приложении и тема туда-сюда переключается на ночную/дневную, с оригинальным приложением никаких вопросов не было. Сейчас день и тема не переключается самопроизвольно, но вечером будет,и так происходит с версии 2+, до этого модифицированная телега не стояла

**Comment by lebovsky-z** [comment]
Переключение может происходить пару раз в минуту, или раз в пару минут, достаточно часто.

**Comment by wrwrabbit** [comment]
Баг может быть также из-за обновлений оригинальной телеги. У вас есть возможность проверить на телефоне последнюю версию оригинального Тг? У нас просто не воспроизводится этот баг а oneplus 7t pro у нас нет.
@vivabelarus ты тестировал на Андроид 11?

**Comment by vivabelarus** [comment]
Да, у меня на эмуляторе Андроид 11. Это описание бага отличается от предыдущих. В предыдущих тема слетала при включении и я не мог воспроизвести. Тут, я так понимаю, стоит адаптивная тема в зависимости от яркости? Может, в датчике проблема?

**Comment by lebovsky-z** [comment]
vivabelarus, вы оказались правы. Стояла именно адаптивное переключение темы, а не по расписанию (не заметил, что после установки мода настройки поменялись). Поставил "по расписанию", сегодня вечером проверю

**Comment by lebovsky-z** [comment]
Проблема оказалась в датчике освещенности, а не в телеге. Поменял смену темы на "по расписанию" и резкие переключения пропали
