### ISSUE TITLE
MD5 hash for builds

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#23]
MD5 как стандарт хеширования был разработан в 1991 году для создания уникального хеш-кода от заданного значения с последующей проверкой его подлинности.

Утилита md5sum, предназначенная для хеширования данных заданного файла по алгоритму MD5, возвращает строку. Она состоит из 32 чисел в шестнадцатеричной системе исчисления (016f8e458c8f89ef75fa7a78265a0025).
То есть хеш, полученный от функции, работа которой основана на этом алгоритме, выдает строку в 16 байт (128) бит. И эта строка включает в себя 16 шестнадцатеричных чисел. При этом изменение хотя бы одного ее символа приведет к последующему бесповоротному изменению значений всех остальных битов строки:
Как пользоваться md5sum?
-https://www.tecmint.com/generate-verify-check-files-md5-checksum-linux/
Для Андроид?
-https://play.google.com/store/apps/details?id=com.hobbyone.HashDroid&hl=en&gl=US
Termux?
-https://marisharingilmu.wordpress.com/tag/how-to-check-md5sum-on-termux-android/

**Comment by Bulbachka** [comment]
MD5 уже давно скомпрометирован, нужно использовать другую хэш функцию

**Comment by wrwrabbit** [comment]
Предлагайте альтернативу

**Comment by Bulbachka** [comment]
Blake2, SHA3

**Comment by wrwrabbit** [comment]
@Bulbachka Есть простой способ работать с sha3 на винде и маке?

**Comment by Bulbachka** [comment]
> @Bulbachka Есть простой способ работать с sha3 на винде и маке?

Поставить OpenSSL под любую ось и использовать `openssl sha3-256 path` (`blake2b512`)

Например:
`D:\>openssl sha3-256 iris.data
SHA3-256(iris.data)= ddd806a030a5f4708952189f8a7f78a73df4c15cad2006a4151210509b1f58de
`
или
`D:\>openssl blake2b512 iris.data
BLAKE2b512(iris.data)=1d3b46ca8cb6495e39ca46df075ffefc9b3fb0cb7abb146777ec24237cf83741e395cc6e338641f82b8c1b6e54b0a753f778106adcf177a68e720fa584f51ced`

**Comment by a-klimashevsky** [comment]
MD5 только покажет , что файл в сообщении соотв. хешу в сообщении.
если злоумышленник имеет доступ к сообщению (что-бы поменять ссылку на apk) то он поменяет и md5

android-приложение подписывается сертификатом ( а там sha-265) так почему-бы не воспользоваться этим?
из плюсов сертификат с приватным ключем находится только у разработчика

**Comment by a-klimashevsky** [comment]
вот одна из статей на тему https://dev.webonomic.nl/how-to-check-a-the-certificate-on-an-android-app-apk

**Comment by wrwrabbit** [comment]
> MD5 только покажет , что файл в сообщении соотв. хешу в сообщении.
> если злоумышленник имеет доступ к сообщению (что-бы поменять ссылку на apk) то он поменяет и md5
> 
> android-приложение подписывается сертификатом ( а там sha-265) так почему-бы не воспользоваться этим?
> из плюсов сертификат с приватным ключем находится только у разработчика

мы можем добавить md5\sha на гитхабе вместе с release
