### ISSUE TITLE
Возможность удалить все свои сообщения из беседы

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#24]
менты активно юзают граберы групповых чатов. И ещё оч много OSINT ботов которые также парсят всё из групповых чатов. Поэтому если запилить функцию удаления всех своих отправленных сообщений из группового чата, а также предлагать это сделать каждому человеку, когда из какой-то конференции выходит, то стало бы чуть безопаснее

**Comment by vivabelarus** [comment]
@ivanovivan12589, не хочешь этим заняться?

**Comment by ivanovivan12589** [comment]
Давай, заодно буду улучшать чуть что обычные удаления

**Comment by vivabelarus** [comment]
А как их надо улучшать?

**Comment by ivanovivan12589** [comment]
Есть вариант переписать отправку и удаление на запросы к серверам, чтобы не ловить потом сообщения, плюс фиксить баги, которые будем находить
