### ISSUE TITLE
Send a telegram message on faulty login

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#25]
On faulty login send a telegram message (like the SMS feature)

**Comment by wrwrabbit** [comment]
@ivanovivan12589 мы хотим выпустить версию  последними обновлениями оригинального телеграма. Каков прогресс с #25 ?

**Comment by ivanovivan12589** [comment]
Постепенно кожу, но сложно со свободным временем. 
Сейчас встраиваю логику, но не могу рассчитать, когда закончу. Постараюсь к выходным, но не могу быть уверен. Поэтому, думаю, лучше выложить без моего
