### ISSUE TITLE
advanced forward

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#275]
при пересылке сообщения таким образом меняется автор сообщения на того, кто переслал (то есть как будто ты скопировал, вставил текст сообщения и отправил, но при этом сохраняются все фото и форматирование). А так соо отправлено как будто от тебя, то его ещё и можно отредактировать

Удобно, когда надо передать информацию, не светя изначального автора сообщения

**Comment by vivabelarus** [comment]
А в чём суть предложения?

**Comment by wrwrabbit** [comment]
не светить изначального автора сообщения

**Comment by vivabelarus** [comment]
Ну я к тому, что нужно сделать? Сделать, чтобы по умолчанию скрывались имена?

**Comment by wrwrabbit** [comment]
нет. чтобы было два варианта пересылать сообщения. один обычный, другой от своего имени (copy_message).

**Comment by vivabelarus** [comment]
Так такая фича есть в оригинале

**Comment by wrwrabbit** [comment]
А где ты такое видел? не нахожу

**Comment by vivabelarus** [comment]
Выбери сообщение для пересылки и выбери в какой чат переслать. В чате над полем ввода будет пересылаемое сообщение и тебе остаётся нажать на кнопку отправки. Вот в этот момент нажимаешь на пересылаемое сообщение. Будет предложено скрыть имя отправителя. Тогда отправится весь контент без указания имени отправителя. Как будто ты скопировал сообщение и сам отправил.

**Comment by wrwrabbit** [comment]
Круто. Пропустил этот момент
