### ISSUE TITLE
Сбивается форматирование в сообщениях иноагентов

### ISSUE THREAD

**Issue by tomilovsenya** [wrwrabbit/Partisan-Telegram-Android#300]
В постах, откуда удаляется "ебала" про иностранное агентство (при включении соответствующей партизанской опции), сбивается форматирование: жирный шрифт, ссылки и всё в этом духе. Очевидно, из-за удаления этого куска сообщения.

**Comment by vivabelarus** [comment]
Будет исправление в следующей версии
