### ISSUE TITLE
Добавьте дисклеймер, что партизанский телеграм не даёт стопроцентной защиты 

### ISSUE THREAD

**Issue by akokuliuk** [wrwrabbit/Partisan-Telegram-Android#319]
В детали вдаваться не буду, но напомните юзерам что нужно использовать автоудаление сообщений и секретные чаты. Не претендуйте на то, что вы что-то защитите. Детали могу рассказать автору репы в лс

**Comment by vivabelarus** [comment]
Если есть факты того, что что-то работает не так, как предполагает пользователь, пишите в https://t.me/partisan_telegram_bot
