### ISSUE TITLE
Можно сделать точки вместо подчёркиваний?

### ISSUE THREAD

**Issue by midex63** [wrwrabbit/Partisan-Telegram-Android#348]
Возможно ли для удобства, что бы в релизах было имя PTelegram.apk
Или хотя бы PTelegram-v2.19.26.apk. (вместо подчёркиваний точки)
Тогда можно было бы скачать всегда самую последнюю версию после вот так: 
`wget https://github.com/wrwrabbit/Partisan-Telegram-Android/releases/latest/download/PTelegram.apk`

**Comment by vivabelarus** [comment]
Сделано: https://github.com/wrwrabbit/Partisan-Telegram-Android/releases/download/2.19.32/PTelegram.apk
