### ISSUE TITLE
Показывать удаленные собеседником сообщения

### ISSUE THREAD

**Issue by nawinds** [wrwrabbit/Partisan-Telegram-Android#363]
Можно ли сделать, чтобы сообщения, удаленные собеседником, но уже доставленные на устройство, не удалялись в PTelegram, а лишь помечались, как удалённые. Например, иконкой 🚫

**Comment by vivabelarus** [comment]
Это запрещено пунктом 1.4 в условиях использования API Telegram: https://core.telegram.org/api/terms
