### ISSUE TITLE
Telegram web version instead of play store

### ISSUE THREAD

**Issue by javad94** [wrwrabbit/Partisan-Telegram-Android#384]
Hi, why ptelegram switched from org.telegram.messenger to org.telegram.messenger.web package name?

**Comment by vivabelarus** [comment]
Hello. We decided that we could more successfully disguise PTelegram as a standalone version of the official Telegram than as a Play Market version. When we disguised the application as org.telegram.messenger, there were some signs that made it clear that the application was not installed from the Google Play. Perhaps we will build the org.telegram.messenger version again, but it will not be the main one.
