### ISSUE TITLE
Publishing on F-Droid

### ISSUE THREAD

**Issue by danialbehzadi** [wrwrabbit/Partisan-Telegram-Android#385]
Hey,

It would be nice to have this app on F-Droid too.
Are you okay with including it there?

**Comment by vivabelarus** [comment]
Hello.

We don't mind publishing this app on F-Droid, but there is a big problem. We disguise our application as the original telegram. The id of our application matches one of the id of the official Telegram: org.telegram.messenger.web. With this in mind, we doubt that our application will comply with the rules of the main F-Droid repository.
