### ISSUE TITLE
Prevent telegram to log my actual IP

### ISSUE THREAD

**Issue by foremtehan** [wrwrabbit/Partisan-Telegram-Android#394]
It would be great if you add some setting that prevent telegram to log my actual IP.

For example, I want to always connect to VPN, So if i accidentally disconnected wait for my VPN ip rather than my real IP

Hint: Add a field and ask for country name so i could never connect from specific country.

**Comment by vivabelarus** [comment]
Why not use the built-in proxy feature? In this case, you do not have to turn on the VPN every time. Except the first time, of course, when you log into your account.

**Comment by wrwrabbit** [comment]
You can also turn on TOR browser and set in Telegram proxy 127.0.0.1:9150 (or 9050) to route your traffic through TOR
