### ISSUE TITLE
Multiple actions and account-specific actions 

### ISSUE THREAD

**Issue by vivabelarus** [wrwrabbit/Partisan-Telegram-Android#41]
Сейчас с настройкой действий есть 2 проблемы:

1. Есть действия, которые, по идее, должны добавляться в произвольном количестве. Например, должна быть возможность отправить смски произвольному количеству контактов, отправить сообщение произвольному количеству контактов. Всё это уже реализовано в каком-то виде. Но, как по мне, кривовато. 
2. Есть действия, которые привязаны к аккаунту. Например, для того, чтобы настроить выход из аккаунта, необходимо зайти в настройки с этого аккаунта и выбрать это действие. Если надо настроить для другого аккаунта выход, нужно заходить в настройки через него. Во-первых, это неудобно. Во-вторых, пользователь может подумать, что настройка применилась ко всем аккаунам, а не только к текущему.

Поэтому надо подумать, как переделать действия, чтобы их настройка была user friendly. 

Я изначально хотел сделать список действий. Если нужно новое действие, нажимается кнопка "добавить" и появляется activity, на которой можно выбрать действие для добавления. Одиночные действия исчезают из этого списка после добавления. Множественные действия можно добавлять сколько угодно раз. И можно менять их порядок, удалять.

Сейчас я не уверен, что такой подход правильный. Возможно, проще будет сделать отдельные activity для sms и телеграммных сообщений, в которых можно их настроить. Просто чтобы не засорять общий список действий.

И как поступаем с действиями, настраиваемыми на аккаунт? Сделать внизу список аккаунтов и уже на activity каждого аккаунта настраивать действия?

@wrwrabbit, @ivanovivan12589, хотелось бы услышать ваше мнение.

**Comment by ivanovivan12589** [comment]
1. Согласен, надо бы вынести в отдельное окно настроек, чтобы не заполнять ими другие настройки.
2. Как по мне, тот факт, что пароль настраивается на аккаунт не такой уж неочевидный, потому что другие настройки работают в телеграмме так же. Поэтому тут я бы спросил напрямую у пользователей, удобен ли им текущий вариант или надо переделать в общие настройки на несколько аккаунтов. По-моему, настройки по аккаунтам -- хорошая идея.
3. Думаю, что отдельное окно с возможностью добавить будет не сильно удобнее обычного набора с возможностью enabled-disabled.
Поэтому, по моему мнению, произвольные действия надо бы вынести в отдельное activity, оставив в основном списке возможность их включить/выключить, а остальное оставить, как есть.

**Comment by vivabelarus** [comment]
1 и 3 принял. По поводу 2 поясню.

Вот как раз пароль настраивается не на аккаунт, а на всё приложение. Но отдельные настройки в нём настраиваются именно на аккаунты. Например, при входе с ложным паролем кэш будет очищаться для всех аккаунтов. А выход будет производиться из всех аккаунтов. Поэтому нужно как-то дать понять.

**Comment by vivabelarus** [comment]
1 и 3 принял. По поводу 2 поясню.

Вот как раз пароль настраивается не на аккаунт, а на всё приложение. Но отдельные настройки в нём настраиваются именно на аккаунты. Например, при входе с ложным паролем кэш будет очищаться для всех аккаунтов. А выход будет производиться из всех аккаунтов. Поэтому нужно как-то дать понять пользователю, что конкретная настройка связана только с этим аккаунтом.

Есть следующие варианты:

1. Как-то отметить, что настройка привязана к аккаунту. Например, как на скрине ниже. Здесь я такие настройки отметил при помощи emoji. Если будем такой вариант реализовывать, поставим там аву соответствующего аккаунта.
![Screenshot_](https://user-images.githubusercontent.com/74508922/109389945-d3d79480-791f-11eb-9984-f82ef793588e.png)

2. Перечислить все аккаунты и вынести все соответствующие настройки на activity каждого аккаунта. Тут тоже вместо emoji будут авы из аккаунтов.
![Screenshot_4](https://user-images.githubusercontent.com/74508922/109390368-48133780-7922-11eb-9107-08da04e89955.png)

**Comment by vivabelarus** [comment]
Вообще да, можно сделать голосование на канале за оба варианта или за оставление как есть.

**Comment by wrwrabbit** [comment]
Давай №2, только текст "account specific actions" может лучше над списком юзеров? А не под

**Comment by vivabelarus** [comment]
Да, сделаю так. Ну то есть внизу описание, вверху заголовок
