### ISSUE TITLE
Chats screen briefly visible?

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#43]
Тестирую крайнюю версию телеграмма. Перед запросом пароля высвечивает на секунду экран с каналами. В официале такого не было. У меня андроид.

**Comment by vivabelarus** [comment]
Проверил официальное приложение. В нём тоже вижу на секунду экран с каналами перед запросом пароля. Для того, чтобы избежать этого, необходимо запретить снимки экрана в настройках кода-пароля.
