### ISSUE TITLE
Hide phone on account creation by default

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#44]

**Comment by vivabelarus** [comment]
Я так понимаю, другие настройки приватности тоже выставить более жёсткими. Запретить звонки всем кроме контактов, запретить видеть последнюю активность. Я думаю, это те настройки, которые обязательно нужны в партизанском аккаунте по умолчанию. Насчёт отображения фото профиля, приглашения в группы и пересылки сообщений я не уверен.

**Comment by wrwrabbit** [comment]
Да. Может даже спросить юзера на логине/регистрации - "Вы хотите пользоваться аккаунтом анонимно?" Если да то все настройки на макс анонимность.
Еще идея, если юзер выбирает номер +375 то предупредить что это не безопасно по .... причинам.

**Comment by vivabelarus** [comment]
Closed in #46
