### ISSUE TITLE
Вылет приложения

### ISSUE THREAD

**Issue by MarloGrayhat** [wrwrabbit/Partisan-Telegram-Android#455]
Если ввожу фейковый пароль, то приложение вылетает и после этого вход не возможен. 

Установленна последняя версия из релизов

Шаги к вылету:
1) вошёл в основной акк.
2) добавил пароль для него
3) создал пароль для 2 аккаунта
4) спрятал 1 канал
5) вышел в меню
6) нажал на замочек
7) ввел файловый пароль

Такое происходит только после установки чатов/каналов для удаления/скрытия. Если просто создать фейковый аккаунт, то вход будет происходить нормально

P.S. еще раз переустановил сделал все тоже самое, но не прятал канал. Проблема осталась.

**Comment by MarloGrayhat** [comment]
Сегодня снова попробовал зайти итог на фото

![Screenshot_2023-09-14-12-15-24-85_0b342c26d6c44f3c8d2de40eabb4e1da.jpg](https://github.com/wrwrabbit/Partisan-Telegram-Android/assets/114166594/1d6df7ef-c88b-4469-9304-2950d95947cb)

**Comment by PiIigrim** [comment]
Такая же проблема, ложный код пароль крашит приложение до состояния невозможности зайти(приходится переустанавливать), такое происходит и в обычном и в безпарольном режиме 
Проблема начала появляться после того как установил последнне обновление прошивки на телефон(Samsung S20FE), до этого никаких проблем небыло. Пробовал установить прошлую версию, но проблема остаётся.

**Comment by MarloGrayhat** [comment]
> Такая же проблема, ложный код пароль крашит приложение до состояния невозможности зайти(приходится переустанавливать), такое происходит и в обычном и в безпарольном режиме 
> Проблема начала появляться после того как установил последнне обновление прошивки на телефон(Samsung S20FE), до этого никаких проблем небыло. Пробовал установить прошлую версию, но проблема остаётся.

Прошлую версию программы или прошивки телефона?

**Comment by PiIigrim** [comment]
Телеграмма, с 3.4.5 до 3.4.4

**Comment by PiIigrim** [comment]
С последним обновлением(3.4.6) проблема решена
