### ISSUE TITLE
This message is not supported by your version of Telegram

### ISSUE THREAD

**Issue by mtxadmin** [wrwrabbit/Partisan-Telegram-Android#466]
Часто в комментариях сообщения отображаются так:

"This message is not supported by your version of Telegram. Update the app to view"

PTelegram 3.4.7 (на данный момент это [latest release](https://github.com/wrwrabbit/Partisan-Telegram-Android/releases))

**Comment by mtxadmin** [comment]
Апдейт: в пререлизе [3.5.0](https://github.com/wrwrabbit/Partisan-Telegram-Android/releases/tag/3.5.0) эта проблема, похоже, не наблюдается.

**Comment by mtxadmin** [comment]
(Зато в 3.5.0, похоже, отвалился беспарольный вход, но это #468. Просто для понимания, что предрелиз не идеален)

**Comment by vivabelarus** [comment]
Это сообщение появляется тогда, когда версия оригинала, на которой основан партизанский телеграм, отстаёт от последней официальной версии. Если видите такое, значит, мы скоро обновим партизанский телеграм.

**Comment by mtxadmin** [comment]
Для информации: про отваливание беспарольного входа - это я был неправ. Про крэш при тапе на комменты - [тоже](#469).

В общем, предрелиз вполне себе стабильный и безошибочный.
