### ISSUE TITLE
Сломался беспарольный вход

### ISSUE THREAD

**Issue by mtxadmin** [wrwrabbit/Partisan-Telegram-Android#468]
В пререлизе 3.5.0, похоже, сломался беспарольный вход

В последнем релизе 3.4.7 - работал

Как вариант, это я что-то не то повторяю в настройках (хотя там одна галка, но), либо же чуть изменилась логика

**Comment by vivabelarus** [comment]
Что значит "сломался"? Что именно не работает? Как проявляется?

**Comment by mtxadmin** [comment]
И с включенной, и с выключенной галкой Passwordless Mode - в любом случае выдает ввод пин-кода

**Comment by vivabelarus** [comment]
Беспарольный режим включается после ввода соответствующего ложного код-пароля. Для того, чтобы он включался автоматически, нужно настроить активацию этого ложного по таймеру.

**Comment by mtxadmin** [comment]
Да, вы правы. Это я ошибся при перенастройке. Извините.
