### ISSUE TITLE
Пример в документацию

### ISSUE THREAD

**Issue by mtxadmin** [wrwrabbit/Partisan-Telegram-Android#469]
В копилку странных, но логичных глюков - если канал оставить "в общем доступе" , а его группу-обсуждалку случайно добавить на скрытие, то всё работает, но при тыкании на строчку с комментами приложение вываливается.

Добавьте в документацию, пожалуйста, пример, как не надо делать :-)

**Comment by vivabelarus** [comment]
Что значит "вываливается"? Закрывается? В описанном случае комменты должны просто не открываться.
