### ISSUE TITLE
Не обновляются каналы после входа по код паролю

### ISSUE THREAD

**Issue by Bigorat** [wrwrabbit/Partisan-Telegram-Android#499]
После обновления на любую версию после 10.6.1 (3.5.6) при входе и вводе код пароля не обновляются каналы на наличие новых сообщений. Если зайти в настройки управления памяти и сделать очистку базы данных в ручную, появляются новые записи со счётчикам сообщений.

**Comment by vivabelarus** [comment]
Здравствуйте. Подскажите, как этот баг воспроизвести? Может, у Вас какие-то особые настройки ложного код-пароля установлены?

**Comment by Bigorat** [comment]
Добрый день. Я не могу сказат как воспроизвести баг, потому что на старой версии (10.6.1) его нет. В версии 10.6.1 при входе в приложение со вводом пароля в строке поиска открывается список скрытых каналов, и справа рядом с ними при наличии новых сообщений есть счетчики сообщений. После обновления поверх старой версии на новую ничего не меняя при этом, и при таком же входе уже в новом приложении данныене обновляются. А если зайти в настройки хранилища и сделать очистку базы данных то сразу добавляются новые сообщения в каналы. Уже пробовал и так и эдак,меня код пароли, ничего не помогает. Можно зайти к вечеру в аккаунт по код паролю и не будет никаких новых сообщений за день, пока не сделаешь очистку базы данных. Как только выполнишь такую манипуляцию сразу появляется куча новых сообщений со счетчиками как и должно быть при входе.

**Comment by vivabelarus** [comment]
Да, при "жёстком" скрытии чаты могут не обновляться при входе с оригинальным код-паролем.
