### ISSUE TITLE
Физически удалять данные при очистке кэша

### ISSUE THREAD

**Issue by rfs-dev** [wrwrabbit/Partisan-Telegram-Android#519]
Очистка кэша нужна для удаления компрометирующих двнных с телефона. Партизанский телеграм позволяет очистить кэш по вводу ложного кода-пароля. Кроме того, кэш можно очистить в настройках телеграма.

Однако при удалении файлов данные остаются на носителе. Средства восстановления данных позволяют восстановить удалённые файлы. Российские и белорусские силовики используют программно-аппаратные комплексы Cellebrite UFED и "Мобильный криминалист" (https://www.youtube.com/watch?v=Ib4jFJrrgu8), которые предоставляют такую функцию.

Поэтому файлы кэша нужно удалять физически, чтобы на носителе не оставалось данных. Например, перезаписывать данные последовательностью нулей. Аналогично работает приложение iShredder.

**Comment by vivabelarus** [comment]
Всё не совсем так. Все анроид-устройства начиная с Android 10 должны использовать File Based Encryption (https://cellebrite.com/en/glossary/file-based-encryption-mobile-device-forensics/). Это означает, что Cellebrite UFED и подобные устройства, скорее всего, не смогут восстановить удалённые файлы.

В случае с Телеграмом проблема в том, что кроме "Кэша" как такового, в котором хранятся медиа, есть ещё "база данных", которая, по своей сути, является кэшем сообщений и некоторых других данных. И данные из неё можно восстановить при помощи подобных устройств. На данный момент мы экспериментируем с тем, чтобы добавить возможность для чатов, которые не должны быть видны (скрытые чаты, чаты для удаления, чаты в скрытых аккаунтах, чаты в аккаунтах с логаутом), в принципе не хранить сообщения на устройстве, а загружать их каждый раз с сервера.

Кроме того, проблемой является то, что при прямом доступе к файловой системе можно извлечь сессию, и при помощи неё скачать данные, которые не были в кэше. Возможно, в будущем мы добавим что-то типа "секретных аккаунтов", файлы которых будут зашифрованы при помощи пароля пользователя. В таком случае сессией не удастся воспользоваться без знания пароля.
