### ISSUE TITLE
Сообщение не удаляется

### ISSUE THREAD

**Issue by wrwrabbit** [wrwrabbit/Partisan-Telegram-Android#52]
Здравствуйте! По поводу PTelegram-v2_0_0. При установке ложного пинкода с настройками отправить сообщение и выйти из аккаунта, при последующей регистрации остается видно отправленное сообщение. Просто при отправке оно локально удаляется, а в комплекте с выходом из аккаунта, наверно выход происходит первым и отправленное сообщение не удаляется.

**Comment by ivanovivan12589** [comment]
Понял, буду смотреть

**Comment by ivanovivan12589** [comment]
С полной уверенностью сказать не могу, потому что эта подгрузка сообщений с сервера всплыла для меня неожиданно) Но я займусь этим, постараюсь сделать.

**Comment by ivanovivan12589** [comment]
Как я понял, именно комбинация такого действия с выходом не удаляет сообщение. 
Ждать, думаю, не вариант, потому что пользователю хочется выйти побыстрее. Есть вариант помимо удаления помечать их как удаленные и в процессе входа не подгружать (если это вообще возможно), либо же завести очередь на удаление и вместе с выходом/входом её сохранять/загружать и специально чистить сообщения из неё при входе. Что думаете?

**Comment by vivabelarus** [comment]
Можно помечать, но дальше что? Если будет произведён выход из акка, их же не получится удалить. Как вариант, можно делать наоборот. Скрывать акк, из которого необходимо разлогиниться и после отправки сообщений производить реальный выход

**Comment by ivanovivan12589** [comment]
Так тоже вариант.
Я предлагал либо сохранять это как часть сообщения, либо создать очередь из id, которые надо удалить, которую уже сохранить при выходе. При  входе же пройтись по ней и поудалять сообщения.

**Comment by ivanovivan12589** [comment]
Хм, а какие подводные камни есть у отложенного выхода, кроме возможного прохода сообщений? Вдруг что вспомнится сходу.
Я бы просто пока попробовал что-то из тех двух вариантов и если не получится сделать нормально, то перейти к варианту отложенного выхода.

**Comment by vivabelarus** [comment]
А, понял. Но это не везде будет работать. Первый вариант сработает только если этот акк залогинится через партизанскую телегу. Второй вариант вообще будет работать только на этом устройстве. Не очень хорошо. 

Вообще я вижу идеальным следующий сценарий. Если настроена отправка сообщения и выход из акка, то проверяем сеть. Если сети нет, то просто забиваем. Если сеть есть, ждём удаления сообщений. Но не очень долго. Если не дождались удаления, разлогиниваемся. Какие тут могут быть подводные камни, если выставлять небольшие задержки?

**Comment by vivabelarus** [comment]
Или такая схема слишком сложная?

**Comment by ivanovivan12589** [comment]
Схема вроде несложная, но надо аккуратно подобрать время ожиданиея тогда.
Из подводных я вижу только, что если это время истечет, то сообщения не удалятся, и мы вернемся в начало (сеть слабая, например, что делает отклик сервера медленным). Может, в таком случае оставлять какой флаг `dirty`, и при новом входе запускать процедуру осмотра сообщений на предмет совпадающих?

**Comment by vivabelarus** [comment]
Ну вообще да, можно сделать комбинацию методов. Сохранять локально список id сообщений, которые не успели отправиться и удалять их при новом входе.
А про какой флаг речь? Можно как-то сохранить метаинформацию о сообщении на сервере?

**Comment by ivanovivan12589** [comment]
Локальный флаг, который сохраним через конфиг вместо списка `id`. Со списком я, может, поторопился, потому что есть `notify` от сервера, который может не успеть отработать, поэтому флаг как его замена.
Глобально не сильно понятно, как это сделать, потому что про сохранение с метаинформацией я не знаю, надо будет смотреть

**Comment by vivabelarus** [comment]
Ну так если произойдёт выход из акка, то и локальные сообщения, наверное, потрутся. Вместе с их флагами. Вот id могли бы оставаться. Но да, новый id может не прийти. Ну тогда можно сохранять тот же `Map<Integer, String> chatsToSendingMessages` куда-нибудь и по нему потом смотреть. А, чтобы не промахнуться, можно ещё время отправки сохранять, например.

**Comment by ivanovivan12589** [comment]
Флаг сохраняется на аккаунт, не на сообщение. Он означает, что при входе в аккаунт надо почистить сообщения, которые не удалились перед выходом. Для как раз пройтись по сохраненной мапе в поисках совпадений.
В общем направление я понял, по нему пойду, спасибо:)

**Comment by vivabelarus** [comment]
Тут пока ничего нового?

**Comment by ivanovivan12589** [comment]
Я выяснил, что `SharedConfig` сохраняется, пока активен хотя бы один аккаунт, поэтому пока решил тестить на нем. Я поискал место, где лучше всего добавить удаление и, вроде, нашел: `DialogsActivity`. Удаление вызывается, но ничего не происходит. Но я как посмотрел последний мерж, то понял, что не делал `loadMessage`, и, думаю, в этом причина. Как научусь нормально удалять с помощью `SharedConfig` добавлю хранилище по типу того, что используется в `SharedConfig`.

**Comment by ivanovivan12589** [comment]
И, кажется, нашел причину проблемы: при входе даже после подгрузки диалогов в `DialogsActivity` у контроллера лежит пустой `dialogMessage`. Буду смотреть, какие есть замены и/или способы подгрузить сообщения.

**Comment by vivabelarus** [comment]
Так а как сейчас будет? Сообщения будут удаляться после подгрузки DialogsActivity?

**Comment by ivanovivan12589** [comment]
Первичное удаление будет в `TelegramMessageAction`. Уже если сообщения не успели удалиться, то скорее всего в нем будет стоять проверка на это, после чего удаляться повторно после следующего входа.

**Comment by wrwrabbit** [comment]
"Приложение отправляет сообщение контакту и удаляет его у меня (то есть у отправителя) и не удаляет (логично) у получателя.

Но! Когда мы в обычно ситуации удаляем сообщение, оно исчезает и показывается в списке контактов последнее оставшееся сообщение. В данном же случае - в списке контактов у этого контакта показывается не предыдущее сообщение, а пусто. Может связано с этим.

Надо, наверное, попробовать вам (или попросите в канале), что бы другие попробовали смоделировать такую ситуацию. Я бы тоже сходу не заметил это, просто полез проверять вообще как работает ввод ложного пароля (что бы знать поведение приложения заранее)"

**Comment by ivanovivan12589** [comment]
В 2.5.0 такого не замечаю, хм. В 2.4. один раз промелькнуло. Заметил другую проблему: дважды не отправляется одно и то же сообщение. Возможно, фикс этой проблемы пофиксить и это. Занимаюсь.

**Comment by vivabelarus** [comment]
Я так понимаю, эта ошибка исправлена
