### ISSUE TITLE
Скрытие аккаунтов из списка залогиненных при введении фейк-кода

### ISSUE THREAD

**Issue by nikelborm** [wrwrabbit/Partisan-Telegram-Android#526]
Здравствуйте, очень крутой проект
Было бы замечательно, если бы при вводе ложного кода вообще полностью скрывался один (или несколько) из всех доступных аккаунтов в приложении
у меня несколько аккаунтов. Один из них safe, другой нет. хотелось бы иметь возможность просто вообще скрыть существование второго аккаунта

**Comment by vivabelarus** [comment]
Здравствуйте. Такая опция есть: https://github.com/wrwrabbit/Partisan-Telegram-Android/wiki/Функционал-приложения#скрытие-аккаунта
